### ISSUE TITLE
"@types/node" needed as dependency in order to build

### ISSUE THREAD

**Issue by hildjj** [eslint/rewrite#82]
### Which packages are affected?

- [X] `@eslint/compat`
- [X] `@eslint/config-array`
- [ ] `@eslint/core`
- [ ] `@eslint/migrate-config`
- [ ] `@eslint/object-schema`

### Environment

Node version: v22.4.0
npm version: 10.8.1
pnpm version: 9.4.0
ESLint version: rewrite@1.0.0
Operating System: MacOS 14.5

### What did you do?

- Installed all dependencies with `pnpm i -r`
- `npm run build`

### What did you expect to happen?

Successful build

### What actually happened?

```
❯ npm run build

> eslint-rewrite@1.0.0 build
> node scripts/build.js

Building packages in this order: packages/compat, packages/object-schema, packages/config-array, packages/core, packages/migrate-config
Building packages/compat...

> @eslint/compat@1.1.0 build
> rollup -c && tsc -p tsconfig.esm.json && npm run build:cts


src/index.js → dist/cjs/index.cjs, dist/esm/index.js...
(!) Unresolved dependencies
https://rollupjs.org/troubleshooting/#warning-treating-module-as-external-dependency
node:fs (imported by "src/ignore-file.js")
node:path (imported by "src/ignore-file.js")
created dist/cjs/index.cjs, dist/esm/index.js in 33ms
dist/esm/index.js:2:16 - error TS2307: Cannot find module 'node:fs' or its corresponding type declarations.

2 import fs from 'node:fs';
                 ~~~~~~~~~

dist/esm/index.js:3:18 - error TS2307: Cannot find module 'node:path' or its corresponding type declarations.

3 import path from 'node:path';
                   ~~~~~~~~~~~


Found 2 errors in the same file, starting at: dist/esm/index.js:2

npm error Lifecycle script `build` failed with error:
npm error code 2
npm error path .../eslint-rewrite/packages/compat
npm error workspace @eslint/compat@1.1.0
npm error location .../eslint-rewrite/packages/compat
npm error command failed
npm error command sh -c rollup -c && tsc -p tsconfig.esm.json && npm run build:cts
node:internal/errors:983
  const err = new Error(message);
              ^

Error: Command failed: npm run build -w packages/compat --if-present
    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at checkExecSyncError (node:child_process:889:11)
    at execSync (node:child_process:961:15)
    at buildPackages (.../eslint-rewrite/scripts/build.js:109:3)
    at .../eslint-rewrite/scripts/build.js:125:1 {
  status: 2,
  signal: null,
  output: [ null, null, null ],
  pid: 4668,
  stdout: null,
  stderr: null
}

Node.js v22.4.0
```

### Link to Minimal Reproducible Example

n/a

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

This requires an addition of a devDependency for "@types/node" to the `compat` and `config-array` projects.

**Comment by nzakas** [comment]
When I run `npm install && npm run build`, I don't see this error. 

This project doesn't use pnpm. Can you try doing `npm install` and see if that works for you?

**Comment by hildjj** [comment]
It compiles without errors when I use npm to install.  However, I get the following warnings, which are related:

```
(!) Unresolved dependencies
node:fs (imported by "src/ignore-file.js")
node:path (imported by "src/ignore-file.js")

(!) Unresolved dependencies
node:path (imported by "src/config-array.js")
minimatch (imported by "src/config-array.js")
debug (imported by "src/config-array.js")
@eslint/object-schema (imported by "src/config-array.js")
```

Full results:

```
> eslint-rewrite@1.0.0 build
> node scripts/build.js

Building packages in this order: packages/compat, packages/object-schema, packages/config-array, packages/core, packages/migrate-config
Building packages/compat...

> @eslint/compat@1.1.0 build
> rollup -c && tsc -p tsconfig.esm.json && npm run build:cts


src/index.js → dist/cjs/index.cjs, dist/esm/index.js...
(!) Unresolved dependencies
https://rollupjs.org/troubleshooting/#warning-treating-module-as-external-dependency
node:fs (imported by "src/ignore-file.js")
node:path (imported by "src/ignore-file.js")
created dist/cjs/index.cjs, dist/esm/index.js in 25ms

> @eslint/compat@1.1.0 build:cts
> node -e "fs.copyFileSync('dist/esm/index.d.ts', 'dist/cjs/index.d.cts')"

Building packages/object-schema...

> @eslint/object-schema@2.1.4 build
> rollup -c && tsc -p tsconfig.esm.json && npm run build:cts


src/index.js → dist/cjs/index.cjs, dist/esm/index.js...
created dist/cjs/index.cjs, dist/esm/index.js in 32ms

> @eslint/object-schema@2.1.4 build:cts
> node -e "fs.copyFileSync('dist/esm/index.d.ts', 'dist/cjs/index.d.cts')"

Building packages/config-array...

> @eslint/config-array@0.17.0 build
> rollup -c && npm run build:dedupe-types && tsc -p tsconfig.esm.json && npm run build:cts


src/index.js → dist/cjs/index.cjs, dist/esm/index.js...
(!) Unresolved dependencies
https://rollupjs.org/troubleshooting/#warning-treating-module-as-external-dependency
node:path (imported by "src/config-array.js")
minimatch (imported by "src/config-array.js")
debug (imported by "src/config-array.js")
@eslint/object-schema (imported by "src/config-array.js")
created dist/cjs/index.cjs, dist/esm/index.js in 43ms

> @eslint/config-array@0.17.0 build:dedupe-types
> node ../../tools/dedupe-types.js dist/cjs/index.cjs dist/esm/index.js


> @eslint/config-array@0.17.0 build:cts
> node -e "fs.copyFileSync('dist/esm/index.d.ts', 'dist/cjs/index.d.cts')"

Building packages/core...

> @eslint/core@0.1.0 build
> tsc

Building packages/migrate-config...
Done building packages.
```

**Comment by nzakas** [comment]
Those warnings aren't related. They come from Rollup, which knows not to bundle those packages.

I don't know why `pnpm` is giving a different result than `npm`, but as I said, we don't use `pnpm` for this repo, so just stick with `npm` and everything works fine.
